utils::globalVariables(
  c(
    ".",
    "club_url",
    "Country",
    "Name",
    "State",
    "City",
    "Fighters",
    "club_id",
    "club_name",
    "club_country",
    "club_state",
    "club_city",
    "club_members",
    "club_parent_id",
    "event_name",
    "event_year",
    "event_day",
    "event_url",
    "event_id",
    "event_brand",
    "event_date",
    "event_country",
    "event_city",
    "fighter_url",
    "fighter_club_url",
    "fighter_id",
    "fighter_name",
    "fighter_nationality",
    "fighter_club_id",
    "fighter_club_name",
    "get_parent",
    "normalize_names",
    "normalize_countries",
    "normalize_event_names",
    "opponent_id",
    "stage",
    "tournament_category",
    "tournament_name",
    "Stage",
    "fighter_1",
    "fighter_2",
    "hema_clubs",
    "hema_countries",
    "hema_events",
    "hema_fighters",
    "hema_fights",
    "hema_match_results",
    "hema_tournaments",
    "fighter_1_result",
    "fighter_2_result",
    "match_id",
    "tournament_id",
    "tournament_note",
    "tournament_weapon",
    "edges",
    "nodes",
    "Weight",
    "Community",
    "Label",
    "Population",
    "Region",
    "Source",
    "Target",
    "Source_Label",
    "Target_Label",
    "x",
    "y",
    "Id",
    "Line_Type",
    "Sub_Region",
    "region",
    "sub_region",
    "achievement_description_template", "achievement_icon", "achievement_name", 
    "achievement_name_template", "achievement_tier", "alpha_posterior", 
    "animal_tournaments", "beta_posterior", "club_community", "community", 
    "community_label", "event_community", "event_name_normalized", "event_region", 
    "final_matches", "gold_medals", "interval_between_fights", "is_home", "losses", 
    "match_count", "matches_home", "max_countries", "max_events", "max_interval", 
    "max_streak", "max_wins", "percentile", "population", "posterior_mean", "result", 
    "stage_norm", "tier_id", "total_countries", "total_events", "total_fighters", 
    "total_fighters_in_year", "total_matches", "total_wins", "tournament_count", 
    "tournaments_attended", "visited_regions", "weapon_count", "win_rate", "wins"
  )
)

utils::globalVariables(c(
  "achieved", "achievement_description", "achievement_name", 
  "tier_id", "percentile", "achievement_tier", "achievement_icon", 
  "final_matches", "wins", "losses", "event_year", "fighter_id"
))