utils::globalVariables(
  c(
    ".",
    "club_url",
    "Country",
    "Name",
    "State",
    "City",
    "Fighters",
    "club_id",
    "club_name",
    "club_country",
    "club_state",
    "club_city",
    "club_members",
    "club_parent_id",
    "event_name",
    "event_year",
    "event_day",
    "event_url",
    "event_id",
    "event_brand",
    "event_date",
    "event_country",
    "event_city",
    "fighter_url",
    "fighter_club_url",
    "fighter_id",
    "fighter_name",
    "fighter_nationality",
    "fighter_club_id",
    "fighter_club_name",
    "get_parent",
    "normalize_names",
    "normalize_countries",
    "normalize_event_names",
    "opponent_id",
    "stage",
    "tournament_category",
    "tournament_name",
    "Stage",
    "fighter_1",
    "fighter_2",
    "hema_clubs",
    "hema_countries",
    "hema_events",
    "hema_fighters",
    "hema_fights",
    "hema_match_results",
    "hema_tournaments",
    "fighter_1_result",
    "fighter_2_result",
    "match_id",
    "tournament_id",
    "tournament_note",
    "tournament_weapon",
    "edges",
    "nodes",
    "Weight",
    "Community",
    "Label",
    "Population",
    "Region",
    "Source",
    "Target",
    "Source_Label",
    "Target_Label",
    "x",
    "y",
    "Id",
    "Line_Type",
    "Sub_Region",
    "region",
    "sub_region",
    "achievement_description_template", "achievement_icon", "achievement_name", 
    "achievement_name_template", "achievement_tier", "alpha_posterior", 
    "animal_tournaments", "beta_posterior", "club_community", "community", 
    "community_label", "event_community", "event_name_normalized", "event_region", 
    "final_matches", "gold_medals", "interval_between_fights", "is_home", "losses", 
    "match_count", "matches_home", "max_countries", "max_events", "max_interval", 
    "max_streak", "max_wins", "percentile", "population", "posterior_mean", "result", 
    "stage_norm", "tier_id", "total_countries", "total_events", "total_fighters", 
    "total_fighters_in_year", "total_matches", "total_wins", "tournament_count", 
    "tournaments_attended", "visited_regions", "weapon_count", "win_rate", "wins","gold_medal_matches"
  )
)

utils::globalVariables(c(
  "achieved", "achievement_description", "achievement_name", 
  "tier_id", "percentile", "achievement_tier", "achievement_icon", 
  "final_matches", "wins", "losses", "event_year", "fighter_id"
))


utils::globalVariables(c(
  "achievement_id", "alpha-3", "alpha_2", "category", "category_id",
  "category_source", "category_source_id", "club", "club_country_id",
  "club_source", "club_source_id", "country-code", "country_code", "country_id",
  "created_at", "cumulative_count", "debut_date", "debut_fight", "deleted",
  "distinct_countries", "distinct_scenes", "elo.A", "elo.B", "elo_1", "elo_2",
  "event_country_id", "event_source", "event_source_id", "fencer_population",
  "fighter1_score", "fighter_count", "fighter_debut_fight", "fighter_elo",
  "fighter_elo_gain", "fighter_source", "fighter_source_id", "fighter_win_chance",
  "fighters_achieved", "fighters_ids", "fighters_total", "first_tournament_date",
  "hema_scene", "hema_scene_id", "intermediate-region", "intermediate_region",
  "is_final", "main_table", "match_date", "match_result_id", "max_year", "min_year",
  "month_date", "name", "opponent_elo", "p.A", "problem", "ranking_category",
  "ranking_source", "ranking_source_id", "rating_id", "result_id", "result_source",
  "stage_type", "tier_count", "tournament_source", "tournament_source_id",
  "update.A", "update.B", "update_1", "update_2", "updated_at", "weapon_id",
  "weapon_source", "weapon_source_id", "weighted_rating", "win_chance", "win_chance_1",
  "win_chance_2", "wins.A"
))